import {
	defineConfig,
	defineAutogeneratedFile
} from "@anio-software/enkore"
import {defineTargetConfig} from "@anio-software/enkore.target-js-node"
import generateExportFile from "./config/enkore/generateExportFile.mts"

export const config: unknown = defineConfig({
	target: {
		name: "js-node",
		options: defineTargetConfig({
			registry: {
				"anioSoftware": {
					url: "https://npm-registry.anio.software",
					authTokenFilePath: "secrets/anio_npm_auth_token",
					clientPrivateKeyFilePath: "secrets/npm_client.pkey",
					clientCertificateFilePath: "secrets/npm_client.cert"
				}
			},

			packageSourceRegistryByScope: {
				"@anio-software": {
					registry: "anioSoftware"
				}
			},

			publish: [{
				registry: "anioSoftware"
			}]
		})
	},

	autogeneratedFiles: [
		defineAutogeneratedFile({
			destinationPath: `project/export/async/__aggregatedExports.ts`,
			generator(session) {
				const generator = generateExportFile("async")

				return generator(session.project.root)
			}
		}),

		defineAutogeneratedFile({
			destinationPath: `project/export/sync/__aggregatedExports.ts`,
			generator(session) {
				const generator = generateExportFile("sync")

				return generator(session.project.root)
			}
		}),

		defineAutogeneratedFile({
			destinationPath: `project/export/default/__aggregatedExports.ts`,
			generator(session) {
				const generator = generateExportFile("default")

				return generator(session.project.root)
			}
		})
	]
})
