export function chmod(...args : any[]) : Promise<any>
export function chmodSync(...args : any[]) : any
export function chown(...args : any[]) : Promise<any>
export function chownSync(...args : any[]) : any
export function copyFile(...args : any[]) : Promise<any>
export function copyFileSync(...args : any[]) : any
export function lstat(...args : any[]) : Promise<any>
export function lstatSync(...args : any[]) : any
export function mkdir(...args : any[]) : Promise<any>
export function mkdirSync(...args : any[]) : any
export function openDirectory(...args : any[]) : Promise<any>
export function openDirectorySync(...args : any[]) : any
export function openFile(...args : any[]) : Promise<any>
export function openFileSync(...args : any[]) : any
export function readFile(...args : any[]) : Promise<any>
export function readFileSync(...args : any[]) : any
export function readdir(...args : any[]) : Promise<any>
export function readdirSync(...args : any[]) : any
export function readlink(...args : any[]) : Promise<any>
export function readlinkSync(...args : any[]) : any
export function realpath(...args : any[]) : Promise<any>
export function realpathSync(...args : any[]) : any
export function rename(...args : any[]) : Promise<any>
export function renameSync(...args : any[]) : any
export function rmdir(...args : any[]) : Promise<any>
export function rmdirSync(...args : any[]) : any
export function stat(...args : any[]) : Promise<any>
export function statSync(...args : any[]) : any
export function symlink(...args : any[]) : Promise<any>
export function symlinkSync(...args : any[]) : any
export function unlink(...args : any[]) : Promise<any>
export function unlinkSync(...args : any[]) : any
export function writeFile(...args : any[]) : Promise<any>
export function writeFileSync(...args : any[]) : any
